### ISSUE TITLE
Provide a Linux version of development environment

### ISSUE THREAD

**Issue by Muko-Tabi** [nyanrus/noraneko#39]
Enable Linux users to test and report bugs for Floorp 12. I understand this project is still in development and is not expected to be stable for daily use, but having people test it would help progress towards the stable release of Floorp 12. Thank you in advance.

**Comment by nyanrus** [comment]
Thank you for using Floorp!

I am currently working in Windows builds, and when that is stabilized, the Pull Request from @surapunoyousei will come here!
Currently noraneko is for devs of Browser Inner JS Codes and CSS.

If you have experience to code in Node.js project, you can try with Firefox binary!
Please check https://noraneko.pages.dev/build/scratch

When I release the linux version, I will close this issue and then you will get the notification.

Are there any questions? Thank you for your concern.

Thank you for reading. Have a nice day!

**Comment by Muko-Tabi** [comment]
Ah, I see, then I won't be bothering you much until the Windows version is stable. I will try to go through the binary to build unofficial Floorp 12 for Linux, hope you won't mind it. Thanks again.

**Comment by surapunoyousei** [comment]
https://github.com/surapunoyousei/noraneko-runtime/

**Comment by surapunoyousei** [comment]
https://github.com/rust-lang/rust/issues/117022

**Comment by surapunoyousei** [comment]
https://github.com/nyanrus/noraneko/pull/64

Once this PR is merged, you will be able to develop Noraneko on Linux!
